apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: us-central1-docker.pkg.dev/lyrical-mason-465314-f4/go-services/apigateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: GCP_PROJECT_ID
              value: "lyrical-mason-465314-f4"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "apigatewaypaymentdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "34.57.113.181"
            - name: apigateway_TOPIC_ID
              value: "apigatewaypayment"
            - name: REDIS_HOST
              value: "redis-master.default.svc.cluster.local:6379"
